<?php

namespace app\admin\controller;

use think\Controller;
use think\Request;

class Deal extends Controller
{
    protected $deal;
    private $city;
    private $category;
    protected function initialize()
    {
        $this->city = model('city');
        $this->category = model('category');
        $this->deal = model('deal');
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        $categorys = array();
        $deal = array();
        $this->category->getNormalFirstCategory($categorys);
        $this->deal->getAllDeal($deal);
        foreach ($deal as $k => $v) {
            foreach ($categorys as $category) {
                if ($v['category_id'] == $category['id']) {
                    $deal[$k]['category_name'] = $category['name'];
                }
            }
        }
        //
        return $this->fetch('', compact('citys', 'categorys', 'deal'));
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        //
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
