<?php
namespace app\index\controller;

use think\Controller;

class Index extends Controller
{
    private $deal;
    private $category;
    protected function initialize()
    {
        $this->deal = model('deal');
        $this->category = model('category');
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $title = '首页';
        //垃圾tp5框架
        $deal = array();
        $kaiweicai = array();
        $haochida = array();
        $ret = $this->deal->getAllDeal($deal);
        $this->getDealByType(25, $deal, $kaiweicai);
        $this->getDealByType(26, $deal, $haochida);
        $category = $this->getCategory();
        if (!$ret) {
            $this->error('查询商品失败!!!');
        }

        return $this->fetch('', compact('kaiweicai', 'haochida', 'category', 'title'));
    }

    protected function getDealByType($type, $deal, &$data) {
        $deal = json_decode(json_encode($deal), true);
        foreach ($deal as &$item) {
            $flag = false;
            foreach ($item as $k => $v) {
                if ($k == 'se_category_id') {
                    $category = explode(',', $v);
                    if ($type == $category[1]) {
                        $flag = true;
                    }
                }
                if ($k == 'location_ids') {
                    $location = explode(',', $v);
                    $item['location_count'] = count($location);
                }
            }
            if ($flag) {
                $data[] = $item;
            }
        }unset($item);
        if (!empty($data)) {
            return true;
        }else {
            return false;
        }
    }

    protected function getCategory($categoty_id = 0) {
        $category = array();
        $this->category->getNormalFirstCategory($category, $categoty_id);
        foreach ($category as &$item) {
            $item['sub_category'] = $this->getCategory($item['id']);
        }
        return $category;
    }
}
